#ifndef TOKEN_H
#define TOKEN_H

typedef enum {
    TOKEN_EOF=0,

    /* Identifier */
    TOKEN_IDENT,

    /* Types */
    TOKEN_TYPE_CHAR,
    TOKEN_TYPE_DOUBLE,
    TOKEN_TYPE_BOOLEAN,
    TOKEN_TYPE_INTEGER,
    TOKEN_TYPE_STRING,

    /* Number types */
    TOKEN_INTEGER,
    TOKEN_FLOAT,
    TOKEN_DOUBLE,

    /* Keywords */
    TOKEN_ARRAY,
    TOKEN_AUTO, 
    TOKEN_CARRAY,
    TOKEN_ELSE,
    TOKEN_FALSE,
    TOKEN_FLOAT,
    TOKEN_FOR,
    TOKEN_FUNCTION,
    TOKEN_IF,
    TOKEN_PRINT,
    TOKEN_RETURN,
    TOKEN_TRUE,
    TOKEN_VOID,
    TOKEN_WHILE,

    /* Literals */
    TOKEN_BELL,
    TOKEN_BACKSPACE,
    TOKEN_ESCAPE,
    TOKEN_FORM_FEED,
    TOKEN_NEWLINE,
    TOKEN_CARRIAGE_RETURN,
    TOKEN_TAB,
    TOKEN_VERTICAL_TAB,
    TOKEN_BACKSLASH,
    TOKEN_SINGLE_QUOTE,
    TOKEN_DOUBLE_QUOTE,
    TOKEN_HEXADECIMAL,

    /* Expressions */
    TOKEN_L_PAREN,
    TOKEN_R_PAREN,
    TOKEN_L_BRACKET,
    TOKEN_R_BRACKET,
    TOKEN_FUNCTION_CALL,
    TOKEN_POSTFIX_INCR,
    TOKEN_POSTFIX_DECR,
    TOKEN_UNARY_ARRAY_LEN,
    TOKEN_UNARY_NEGATION,
    TOKEN_LOGICAL_NOT,
    TOKEN_EXPONENTIATION,
    TOKEN_MULT,
    TOKEN_DIV,
    TOKEN_REMAINDER,
    TOKEN_ADD,
    TOKEN_SUB,
    TOKEN_LESS_THAN,
    TOKEN_LESS_THAN_EQ,
    TOKEN_GREATER_THAN,
    TOKEN_GREATER_THAN_EQ,
    TOKEN_EQUAL,
    TOKEN_NOT_EQUAL,
    TOKEN_LOGICAL_AND,
    TOKEN_LOGICAL_OR,
    TOKEN_ASSIGN,


    /* ERROR */
    TOKEN_ERROR
} token_t;

#endif
